### ISSUE TITLE
Error module capa-render

### ISSUE THREAD

**Issue by suricatalfon** [accidentalrebel/mbcscan#1]
Hí,

I have everything I need installed. With python 3.6 and 3.9.

3.6:

```
python3.6 ./mbcscan.py -v
Traceback (most recent call last):
  File "./mbcscan.py", line 13, in <module>
    import capa.main
ModuleNotFoundError: No module named 'capa.main'
```

3.9:

```
$ python3.9 ./mbcscan.py -v

Traceback (most recent call last):
  File "/home/alfon/tools/mbcscan/./mbcscan.py", line 21, in <module>
    from capa.render import convert_capabilities_to_result_document
ImportError: cannot import name 'convert_capabilities_to_result_document' from 'capa.render' (/usr/local/lib/python3.9/dist-packages/capa/render/__init__.py)
```

**Comment by accidentalrebel** [comment]
I'll give this a check. Will get back to you this weekend.

Thanks for reporting this.

**Comment by suricatalfon** [comment]
Thanks   ;-)

**Comment by anisyusof-sc** [comment]
I am experiencing the same error as above. May I know if you manage to check it out? Thanks!

**Comment by accidentalrebel** [comment]
I apologize for not getting back sooner.

I have looked into the problem and have seen that there are a couple of changes on the dependencies. I have done some fixes and would push them once properly implemented and tested.

Thanks!

**Comment by anisyusof-sc** [comment]
That is great, thank you. I will be looking forward to the upcoming update.

**Comment by accidentalrebel** [comment]
Hello, everyone. So the problem was that one of the dependencies (flare-capa) has made changes to the structure of their code. I had to do a few fixes so it should be fine now.

Take note that I have only tested this code on a Windows machine because that's what I currently have access to now. I'll give it a whirl on Linux soon.

Also, if you are using Python 3.10 and are still encountering problems then download the capa repository (https://github.com/mandiant/capa) and install it using pip.

```python -m pip install -e \path\to\capa\```

Install the other dependencies too, just in case

```
python -m pip install mbclib
python -m pip install GitPython
```
This is only temporary fix until flare-capa releases a new version after 3.2.0 on pip.

Thanks!

**Comment by accidentalrebel** [comment]
Please disregard my previous comment.

So the cause of the problem was that the tool hasn't been updated in quite a while and it became outdated when it's main dependency, Capa, has already made a number of new releases.

The fix I mentioned in the previous comment was merely a workaround. So I took the time to properly understand the problem and I ended up with a proper fix. 

Please pull the latest changes and do the following to install the dependencies:

```bash
$ git clone https://github.com/accidentalrebel/mbcscan.git
$ cd mbcscan/
$ pip install -c constraints.txt -r requirements.txt
```

`constraints.txt` makes sure that the latest version of `lief` is installed. This was the cause of the problems in the first place as outlined in [this issue](https://github.com/mandiant/capa/issues/873).
